Repository dirien/minectl, pull requests merged in 2022-09, with the labels that each got.

#620 docs: fix typo
  cmd/minectl/create.go
Labels: size/XS

#621 feat: add dependabot to kick of renovate
  .github/dependabot.yml
Labels: size/S

#626 feat: add ossf scorecard badge
  .github/workflows/ossf-scorecard-action.yaml
  README.md
Labels: size/XS

#627 feat: add ossf scorecard badge flat style
  README.md
Labels: size/XS

#628 feat: add sonarcloud and openssf best pracrtices badge
  README.md
Labels: size/XS

#629 feat: rename module name
  cmd/minectl/create.go
  cmd/minectl/delete.go
  cmd/minectl/list.go
  cmd/minectl/minectl.go
  cmd/minectl/plugins.go
  cmd/minectl/rcon.go
  cmd/minectl/update.go
  go.mod
  go.sum
  internal/progress/progress.go
  internal/provisioner/provisioner.go
  main.go
Labels: size/S

#630 feat: update modules and docs for new Azure GO SDK Auth
  README.md
  go.mod
  go.sum
Labels: size/M

#633 feat: add go reference
  .github/dependabot.yml
  README.md
Labels: size/XS

#634 feat: add go report card badge
  README.md
Labels: size/XS

#640 feat: add GITHUB_TOKEN to lock flow
  .github/workflows/lock.yml
Labels: size/XS
