Repository dirien/minectl, pull requests merged in 2022-01, with the labels that each got.

#346 docs: add link to spot instance chapter
  README.md
Labels: size/XS

#347 fix: typo in name of struct ResourceResults
  pkg/automation/automation.go
  pkg/cloud/aws/aws.go
  pkg/cloud/azure/azure.go
  pkg/cloud/civo/civo.go
  pkg/cloud/do/do.go
  pkg/cloud/equinix/equinix.go
  pkg/cloud/gce/gce.go
  pkg/cloud/hetzner/hetzner.go
  pkg/cloud/ionos/ionos.go
  pkg/cloud/linode/linode.go
  pkg/cloud/multipass/multipass.go
  pkg/cloud/oci/oci.go
  pkg/cloud/ovh/ovh.go
  pkg/cloud/scaleway/scaleway.go
  pkg/cloud/vexxhost/vexxhost.go
  pkg/cloud/vultr/vultr.go
  pkg/provisioner/provisioner.go
Labels: size/L

#358 chore: update papermc to > 1.18 version
  config/papermc/server-aws.yaml
  config/papermc/server-civo.yaml
  config/papermc/server-do.yaml
  config/papermc/server-ionos.yaml
  config/papermc/server-linode.yaml
  config/papermc/server-oci-arm.yaml
  config/papermc/server-oci.yaml
  config/papermc/server-scaleway.yaml
  config/papermc/server-vexxhost.yaml
  config/papermc/server-vultr.yaml
  go.mod
Labels: size/M

#359 chore: update bedrock to > 1.18 version
  config/bedrock/server-civo.yaml
  config/bedrock/server-do.yaml
  config/bedrock/server-equinix.yaml
  config/bedrock/server-gce.yaml
  config/bedrock/server-hetzner.yaml
  config/bedrock/server-ionos.yaml
  config/bedrock/server-linode.yaml
  config/bedrock/server-oci.yaml
  config/bedrock/server-ovh.yaml
  config/bedrock/server-scaleway.yaml
  config/bedrock/server-vexxhost.yaml
Labels: size/S

#360 chore: update fabric / forge / spigot / bukkuit to > 1.18 version
  config/craftbukkit/server-do.yaml
  config/craftbukkit/server-linode.yaml
  config/fabric/server-civo.yaml
  config/fabric/server-do.yaml
  config/fabric/server-linode.yaml
  config/forge/server-do.yaml
  config/forge/server-linode.yaml
  config/spigot/server-azure.yaml
  config/spigot/server-do.yaml
  config/spigot/server-linode.yaml
  internal/template/template_test.go
  internal/template/templates/bash/fabric-binary.tmpl
  internal/template/templates/cloud-init/fabric-binary.yaml.tmpl
Labels: size/M

#361 feat: add lock-inactive support
  .github/workflows/lock.yml
Labels: size/S

#375 feat: add Exoscale as new cloud provider
  README.md
  cmd/minectl/list.go
  cmd/minectl/wizard.go
  config/bedrock/server-exoscale.yaml
  config/java/server-exoscale.yaml
  config/papermc/server-exoscale.yaml
  go.mod
  go.sum
  internal/cloud/cloud.go
  internal/cloud/exoscale/exoscale.go
  internal/cloud/ovh/ovh.go
  internal/common/common.go
  internal/provisioner/provisioner.go
Labels: size/XL

#377 chore: update all versions of the monitoring staack!
  config/papermc/server-vultr.yaml
  internal/template/template_test.go
  internal/template/templates/bash/monitoring-binaries.tmpl
  internal/template/templates/cloud-init/monitoring-binaries.yaml.tmpl
Labels: size/L

#380 Ossf
  .github/workflows/ossf-scorecard-action.yaml
Labels: size/S

#382 feat: add OSSF Scorecard Action
  .github/workflows/ossf-scorecard-action.yaml
Labels: size/XS

#383 feat: add OSSF Scorecard Action
  .github/workflows/ossf-scorecard-action.yaml
Labels: size/M

#395 docs: Add Exoscale documentation
  docs/getting-started-exoscale.md
  docs/img/exoscale_add_server.png
  docs/img/exoscale_create_API_key.png
  docs/img/exoscale_game.png
  docs/img/exoscale_get_api_key.png
  docs/img/exoscale_instance_details.png
  docs/img/exoscale_join.png
Labels: size/L

#404 feat: add ArtifactHub support for minectl image
  .goreleaser.yaml
  README.md
Labels: size/M

#407 feat: fix ossf scorecard findings for pining versions
  .github/workflows/ci.yaml
  .github/workflows/lock.yml
  Dockerfile
Labels: size/M

#410 feat: add Harden Runner from step-security
  .github/workflows/ci.yaml
  .github/workflows/lock.yml
  .github/workflows/ossf-scorecard-action.yaml
Labels: size/S

#411 chore: update prometheus and minecraft-exporter
  cmd/minectl/delete.go
  cmd/minectl/list.go
  cmd/minectl/wizard.go
  internal/cloud/azure/azure.go
  internal/provisioner/provisioner.go
  internal/template/template_test.go
  internal/template/templates/bash/monitoring-binaries.tmpl
  internal/template/templates/cloud-init/monitoring-binaries.yaml.tmpl
Labels: size/M

#412 feat: add artifacthub-repo.yml
  artifacthub-repo.yml
Labels: size/XS

#413 feat: fix pipeline permissions
  .github/workflows/ci.yaml
  .github/workflows/lock.yml
Labels: size/S

#414 feat: add SECURITY.md
  SECURITY.md
Labels: size/M

#424 feat: fix actions with renovate annotation
  .github/workflows/ci.yaml
  .github/workflows/lock.yml
  .github/workflows/ossf-scorecard-action.yaml
Labels: size/M
